set nocompatible

" colors
syntax on
set background=dark

" Set leader to comma.
let mapleader = ","

filetype plugin indent on

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround     " indent to a multiple of shiftwidth

set autoindent
set smartindent

" Show matching brackets.
set showmatch
set mat=5  " for half a sec

" Flexible backspace: allow backspacing over autoindent, line breaks, start of
" insert.
set backspace=indent,eol,start

" This sets soft wrapping:
" set wrap linebreak textwidth=0

" quicker save
nmap <leader>w :w<cr>
" edit and reload .vimrc from inside vim
nmap <silent> <leader>ev :e ~/.vim/vimrc<cr>
nmap <silent> <leader>sv :so $MYVIMRC<cr>
" undo shortcut
nmap <C-u> :u<cr>

" Don't force save when changing buffers
set hidden

autocmd FileType make setlocal noexpandtab

set ruler
set incsearch

" No bell
set visualbell
set noerrorbells

" Ignore some files for filename completion
set wildignore=*.pyc,*.swp

" alternative to ESC
imap <C-n> <Esc>
